### ISSUE TITLE
Zydis.Validator.pas(32,3) Fatal: Cannot find System.Generics.Collections used by Zydis.Validator.

### ISSUE THREAD

**Issue by wonderzdh** [zyantific/zydis-db#1]
hello all, i used lazarus IDE v1.8.4 to build Zydis.Validator.pas.
but i got an error ‘Zydis.Validator.pas(32,3) Fatal: Cannot find System.Generics.Collections used by Zydis.Validator.’.
so, what compiler and IDE are you using?

thanks.

**Comment by flobernd** [comment]
Hi there. It seems like Lazarus/FreePascal does not support this feature (or maybe `{$MODE DELPHI}` has to be used).

I would recommend you to build this project with the free [Delphi Community Edition](https://www.embarcadero.com/products/delphi/starter). This is the same Delphi version I'm using as well.

**Comment by wonderzdh** [comment]
Thank you for your answer, I have installed and used it now.
But I prefer to use the JSON database directly in C++.
